name: deploy-daily

on:
  schedule:
      # Run every day at 6pm
    - cron: '0 18 * * *'

env:
  TWITTER_USER: ${{ secrets.TWITTER_USER }}
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET:  ${{ secrets.TWITTER_CONSUMER_SECRET }}
  TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

jobs:
  setup-build-deploy:
    name: Build and Deploy to Dev
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Test
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Testing
      run: npm test

    - name: Build Site
      run: npm run build:all

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: b09b24c345713c704e71dea8bd81f713
        projectName: jaredwray
        directory: dist
        gitHubToken: ${{ secrets.GH_TOKEN }}
